version: 2.1

executors:
  node:
    parameters:
      tag:
        type: string
    docker:
      - image: circleci/node:<< parameters.tag >>

commands:
  npm_install_with_cache:
    steps:
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-
      - run: npm install

jobs:
  test-v8:
    executor:
      name: node
      tag: "8"
    steps:
      - checkout
      - npm_install_with_cache
      - run: npm test
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  test-v10:
    executor:
      name: node
      tag: "10"
    steps:
      - checkout
      - npm_install_with_cache
      - run: npm test
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

workflows:
  version: 2
  build:
    jobs:
      - test-v8
      - test-v10
