node-base: &node-base
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-npm-deps-{{ checksum "package-lock.json" }}
          - v1-npm-deps-
    - run: npm install
    - run: npm test
    - save_cache:
        key: v1-npm-deps-{{ checksum "package-lock.json" }}
        paths:
          - node_modules

version: 2
jobs:
  test-v8:
    docker:
      - image: circleci/node:8
    <<: *node-base
  test-v10:
    docker:
      - image: circleci/node:10
    <<: *node-base

workflows:
  version: 2
  build:
    jobs:
      - test-v8
      - test-v10
